Repository exercism/bash, pull requests merged in 2021-02, with the labels that each got.

#480 look for exercises in all subdirectories of exercises/
  bin/validate_exercises
Labels: ci

#481 To fix tournament tests in CI without completely revamping the GHA workflows, ...
  exercises/practice/tournament/tournament_test.sh
Labels: ci

#482 bob: add a couple of fiendish tests
  exercises/practice/bob/bob_test.sh
Labels: enhancement

#487 🤖 Add file patterns to config.json
  config.json
Labels: v3-migration 🤖
