Repository exercism/bash, pull requests merged in 2024-01, with the labels that each got.

#650 Syncx
  exercises/practice/dnd-character/.meta/tests.toml
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/perfect-numbers/.docs/instructions.md
  exercises/practice/pythagorean-triplet/.meta/config.json
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/transpose/.meta/config.json
Labels: x:rep/small

#651 Sync leap
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:rep/tiny

#654 sync leap again
  exercises/practice/leap/.docs/introduction.md
Labels: x:rep/tiny

#656 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#659 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
