Repository exercism/bash, pull requests merged in 2024-03, with the labels that each got.

#673 sync recent doc changes
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/say/.docs/instructions.md
  exercises/practice/two-bucket/.docs/instructions.md
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:rep/tiny

#672 sync change exercise
  exercises/practice/change/.meta/tests.toml
  exercises/practice/change/change.bats
Labels: x:rep/small

#674 Sync docs: sieve and darts
  exercises/practice/darts/.meta/config.json
  exercises/practice/sieve/.docs/instructions.md
Labels: x:action/sync, x:size/small, x:rep/small
